projectriff/builder

riff-cnb-buildtemplate.yaml

Fixes #4
To be later integrated in CI (see https://github.com/projectriff/riff-buildpack-group/pull/3) and pushed to GCS with versioned names, but will unlock https://github.com/projectriff/riff/pull/906 for now

Add buildtemplate yaml definition to git

---

.travis/create-builder.sh
.travis/push-buildtemplate-to-gcs.sh
.travis/push-to-dockerhub.sh
README.adoc
riff-cnb-buildtemplate.yaml

Re-instantitate use of the `latest` tag (as well as snapshoted tags as before)
Fixes #6

Rename projectriff/buildpack to projectriff/builder

---

Makefile
integration-tests/go.mod
integration-tests/go.sum
integration-tests/main.go
integration-tests/tests.toml

Fixes #14
This currently requires a custom version of `pack` being installed (built from the 0.0.7 branch)
but this restriction should go away once we upgrade to 0.0.8.

Add integration tests for the builder

---

.travis/push-buildtemplate-to-gcs.sh

The content of the file is pinned to a specific image as the :latest tag
is no longer published.
Refs #18

Restore unversioned builttemplate yaml

---

.travis/push-buildtemplate-to-gcs.sh
riff-cnb-cache.yaml
riff-cnb-clusterbuildtemplate.yaml

Knative supports both BuildTemplate and ClusterBuildTemplate resources.
The advantage of the ClusterBuildTemplate is that it can be maintained
and upgraded as part of riff.
Currently, the template is deployed in each namespace and there is no
mechanism to maintain the template.
This PR also splits out the build cache from the build template. The
cache and service account will still need to be created in each
namespace where builds will run.
There will be a coresponding PR in riff to pull in these changes.
Refs projectriff/riff#968

Switch riff BuildTemplate to be cluster scoped

---

riff-cnb-clusterbuildtemplate.yaml

The builder template is used twice within the build template, as is the
util image. We can centralize the definition of the builder image by
using a parameter. In general, builds should not override the run or
builder image params. It is still useful to parameterize them in order
to make it easier for tooling to discover or update the value cluster
wide.
Refs #22

Parameterize builder and util images in build template

---

riff-cnb-clusterbuildtemplate.yaml

Knative Build 0.3 can produce duplicate build pods which both have the
cache volume mounted in RW mode. Two builds interacting with the cache
at the same time can cause the build to fail.
Slow builds are better than failing builds.
We can reenable the cache with the next version of Knative Build.
Refs knative/build#542

Disable build cache

---

riff-cnb-clusterbuildtemplate.yaml

Individual builds may define their own volume and define the CACHE
argument to use that volume.

Default build cache to an empty dir

---

LICENSE
integration-tests/main.go

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://www.apache.org/licenses/ ([https](https://www.apache.org/licenses/) result 200).
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).

URL Cleanup

---

builder-riff.toml

Buildpacks groups are groups of buildpacks that are designed to work
together. Every non-optional buildpack within a group must pass
detection, otherwise, the next group is tested.
This change switches from all function buildpacks being in a single
group with the riff-buildpack acting as a backstop to having a group per
function buildpack.
One minor semantic change is that the first group to detect wins.
Previously, we could enforce that exactly one function buildpack
detected. On the plus side, we no longer need the riff-buildpack.

Leverage buildpack groups

---

.travis/install-pack.sh
integration-tests/main.go
riff-cnb-clusterbuildtemplate.yaml

Use environment variables instead, now that the function buildpacks are
able to be configured with either riff.toml or environment variables.
Refs projectriff/riff#1192

Drop riff.toml for function config

---

integration-tests/main.go
integration-tests/tests.toml

FATS functions now include a riff.toml file that contains the handler
and artifact values, so we no longer need to specify them. It also drys
up the testcase config by pulling shared values into a common testcase
that is merged into every other testcase.

Updates FATS to latest

---

Makefile
builder-dev.toml

The builder.toml is able to accept a local tgz for a buildpack. We can
reduce local development friction to point at local builds for
function buildpacks that are cloned and built on the developers machine.
This is only a convenience for development and should never be used to
ship a builder image.

Make local testing of function buildpacks easier

---

.travis/install-pack.sh
builder-dev.toml
builder.toml

Updates:
- pack + lifecycle to 0.2.0
- node cnb to 0.0.10
- npm cnb to 0.0.8
- openjdk and build-system cnbs to 1.0.0-M8
Depends on:
- projectriff/command-function-buildpack#7
- projectriff/java-function-buildpack#6
- projectriff/node-function-buildpack#7

bump pack to 0.2.0

---

riff-application-clusterbuildtemplate.yaml
riff-function-clusterbuildtemplate.yaml

Users must provide appropriate credentials for their image registry

Default credential helpers to false

---

.travis/push-buildtemplate-to-gcs.sh

Make it easier for consumers to lock to specific builds while also
being able to track the latest builds for a given version. The CI build
number is published along side releases. There are
The latest build is referenced by branch name:
gs://projectriff/riff-buildtemplate/versions/builds/{branch}
The latest build for a given version is referenced by:
gs://projectriff/riff-buildtemplate/versions/builds/{version}
The latest release for a branch:
gs://projectriff/riff-buildtemplate/versions/releases/{branch}
The latest release for a given version (will never mutate):
gs://projectriff/riff-buildtemplate/versions/releases/{version}

Link version to latest ci builds

---

riff-application-clusterbuildtemplate.yaml

Add analyzed arg to analyze and export steps

---

.travis/push-buildtemplate-to-gcs.sh
riff-application-clusterbuilder.yaml
riff-function-clusterbuilder.yaml

The ClusterBuilder is the kpack equivalent of the Knative Build
ClusterBuildTemplate.
The ClusterBuildTemplates is deprecated, however, we will continue to
publish updates until riff is fully transitioned to kpack.

Publish kpack clusterbuilders for applications and functions

---

Makefile
riff-application-clusterbuilder.yaml
riff-application-clusterbuilder.yaml.tpl

This looks for the first cloudfoundry/cnb image tag that ends with
`-bionic`. It's crude, but works (for now anyway)

Keep the application clusterbuilder up to date

---

builder.toml.tpl
riff-application-clusterbuilder.yaml

It now includes the Node buildpack with the HTTP adapter fix
described in https://github.com/projectriff/streaming-http-adapter/issues/20.

Update builder and base image

---

builder-dev.toml.tpl
builder.toml.tpl
builder.toml.tpl.tpl

* don't depend on pack's default lifecycle
* bump to newest lifecycle release
* pin instead of adding dependabot updates so the platform API compatibility w/ kpack can be managed
* update buildpacks while we are at it

Pin lifecycle

---

.github/workflows/minimal-labels.yml
.github/workflows/tests.yml
.github/workflows/update-bellsoft-liberica.yml
.github/workflows/update-command-function.yml
.github/workflows/update-gradle.yml
.github/workflows/update-java-function.yml
.github/workflows/update-leiningen.yml
.github/workflows/update-maven.yml
.github/workflows/update-node-function.yml
.github/workflows/update-sbt.yml
.github/workflows/update-streaming-http-adapter.yml

Previously, the actions tied to pull requests executed on the pull_request event, which resulted in them not having access to the secrets required for them to execute.  At the beginning of August, GitHub added the pull_request_target event which operates in a similar way except only actions in the base commit would execute ensuring that it was safe to expose secrets. This change updates the pull request actions to use pull_request_target, ensuring that they are always functional.

Pull Request Target

---

.github/workflows/create-builder.yml
.github/workflows/minimal-labels.yml
.github/workflows/tests.yml
.github/workflows/update-bellsoft-liberica.yml
.github/workflows/update-build-image.yml
.github/workflows/update-command-function.yml
.github/workflows/update-draft-release.yml
.github/workflows/update-gradle.yml
.github/workflows/update-java-function.yml
.github/workflows/update-leiningen.yml
.github/workflows/update-maven.yml
.github/workflows/update-node-function.yml
.github/workflows/update-nodejs.yml
.github/workflows/update-sbt.yml
.github/workflows/update-streaming-http-adapter.yml

Previously the Docker Login step in many of the workflows was executed regardless of whether it was necessary.  This would have been find except that the required secrets were not available in PRs from forks.  This change removes the Docker Login steps from where it is not necessary and puts a guard on its execution in workflows that are run as part of PRs.

Docker Login Improvements

---

.github/workflows/update-bellsoft-liberica.yml
.github/workflows/update-build-image.yml
.github/workflows/update-command-function.yml
.github/workflows/update-gradle.yml
.github/workflows/update-java-function.yml
.github/workflows/update-leiningen.yml
.github/workflows/update-lifecycle.yml
.github/workflows/update-maven.yml
.github/workflows/update-node-function.yml
.github/workflows/update-nodejs.yml
.github/workflows/update-sbt.yml
.github/workflows/update-streaming-http-adapter.yml

Previously, the regularly scheduled builds exhausted the free tier of GitHub actions in some orgs.  This change reduces the number of hours and number of days that these scheduled events will run.

Reduced Schedule

---

.github/pipeline-descriptor.yml
.github/workflows/create-builder.yml
.github/workflows/synchronize-labels.yml
.github/workflows/update-bellsoft-liberica.yml
.github/workflows/update-build-image.yml
.github/workflows/update-command-function.yml
.github/workflows/update-draft-release.yml
.github/workflows/update-gradle.yml
.github/workflows/update-java-function.yml
.github/workflows/update-leiningen.yml
.github/workflows/update-lifecycle.yml
.github/workflows/update-maven.yml
.github/workflows/update-node-function.yml
.github/workflows/update-nodejs.yml
.github/workflows/update-pipeline.yml
.github/workflows/update-sbt.yml
.github/workflows/update-streaming-http-adapter.yml

Previously all of the workflows used secrets.GITHUB_TOKEN.  In the end the de-privileged nature of this token proved to be too much and this change migrates the workflows to use bot-specific token instead.

GitHub Token

---

builder.toml

Bumps `lifecycle` from `0.9.2` to `0.9.3`.

Bump lifecycle from 0.9.2 to 0.9.3

---

builder.toml

This change update the builder to use the new preferred docker:// URI format that came along with pack 0.15.0.

Docker URI

---

builder.toml

Bumps `lifecycle` from `0.10.1` to `0.10.2`.

Bump lifecycle from 0.10.1 to 0.10.2
